//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscografiaModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscografiasDBEntities : DbContext
    {
        public DiscografiasDBEntities()
            : base("name=DiscografiasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compañia> Compañia { get; set; }
        public virtual DbSet<Grabacion> Grabacion { get; set; }
        public virtual DbSet<Interprete> Interprete { get; set; }
        public virtual DbSet<Participacion> Participacions { get; set; }
    }
}
