//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscografiaModel.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Participacion
    {
        public int ParticipacionId { get; set; }

		[Required(ErrorMessage ="La Grabacion Es Obligatorio")]
        public int Grabacion_Id { get; set; }

		[Required(ErrorMessage = "El Interprete Es Obligatorio")]
		public int Interprete_Id { get; set; }

		[Required(ErrorMessage = "La Fecha Es Obligatorio")]
		public string Fecha { get; set; }
    
        public virtual Grabacion Grabacion { get; set; }
        public virtual Interprete Interprete { get; set; }
    }
}
